# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: 
      - main
  pull_request:
    types: [opened, syncronize, reopened, closed]
    branches: 
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: atawaflyingcanuck
  AZURE_WEBAPP_PACKAGE_PATH: ''      # set this to the path to your web app project, 

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@main

      - name: 'Run Azure webapp deploy action using publish profile credentials'
        uses: azure/webapps-deploy@v2
        with: 
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE  }} # Define secret variable in repository settings as per action documentation
          package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'
